import type {
  CameraMovement,
  CaptionStylePreset,
  CatalogTemplateId,
  ShotType,
  ThreeEnvironment,
  ThreeLighting,
  TransitionType,
  VideoGenre,
} from '@vc/schema';

type NonEmpty<T> = readonly [T, ...T[]];

/** Motion2D templates only (used for engine-fallback coercion). */
export type Motion2DTemplateId = Exclude<CatalogTemplateId, 'product-turntable' | 'logo-reveal-3d' | 'floating-shapes'>;

/** Creative defaults per genre: guidance for prompts, the heuristic mock, coercion and the compiler. */
export interface GenreProfile {
  genre: VideoGenre;
  label: string;
  /** Pacing guidance (shown to the model). */
  pacing: string;
  tone: NonEmpty<string>;
  audience: string;
  /** Objective template; `{title}` is replaced by the video title. */
  objective: string;
  visualDescription: string;
  typography: string;
  motionLanguage: string;
  /** Default palette (hex), used when the request has no brand colors. */
  palette: NonEmpty<string>;
  /** Body-scene templates in priority order; the first is the genre's hero template. */
  bodyTemplates: NonEmpty<CatalogTemplateId>;
  openingTemplate: CatalogTemplateId;
  /** Final-scene template when there is no call to action. */
  closingTemplate: CatalogTemplateId;
  /** Genre-appropriate motion2d template for engine coercion. */
  fallbackTemplate: Motion2DTemplateId;
  shotTypes: NonEmpty<ShotType>;
  cameraMovements: NonEmpty<CameraMovement>;
  transitions: NonEmpty<TransitionType>;
  moods: NonEmpty<string>;
  /** Narrative beats cycled through the body of the video. */
  beats: NonEmpty<string>;
  /** Chapter title seeds for multi-chapter videos. */
  chapterThemes: NonEmpty<string>;
  defaultCallToAction: string | null;
  threeEnvironment: ThreeEnvironment;
  threeLighting: ThreeLighting;
  captionPreset: CaptionStylePreset;
  /** Narration pace (words per second). */
  wordsPerSecond: number;
  /** Extra creative direction for the model. */
  guidance: string;
}

export const GENRE_PROFILES: Readonly<Record<VideoGenre, GenreProfile>> = {
  'cinematic-ad': {
    genre: 'cinematic-ad',
    label: 'Cinematic ad',
    pacing: 'Fast, rhythmic cuts (~3 s per scene); build tension, then release on the product or brand reveal.',
    tone: ['cinematic', 'aspirational', 'bold', 'emotional'],
    audience: 'Premium consumers who respond to emotion and craft',
    objective: 'Make {title} feel iconic and desirable within seconds.',
    visualDescription:
      'Moody, high-contrast frames with dramatic lighting, shallow depth of field, anamorphic widescreen composition and bold typographic moments.',
    typography: 'Condensed uppercase display type with generous tracking; minimal supporting copy',
    motionLanguage: 'Slow push-ins, light sweeps, match cuts and hard cuts on the beat of the music',
    palette: ['#0B0F1A', '#C8A96A', '#F5F1E8', '#7A1F2B'],
    bodyTemplates: ['kinetic-text', 'floating-shapes', 'quote', 'product-turntable', 'split-feature'],
    openingTemplate: 'title-card',
    closingTemplate: 'logo-reveal-3d',
    fallbackTemplate: 'kinetic-text',
    shotTypes: ['establishing', 'extreme-close-up', 'close-up', 'wide', 'macro', 'insert'],
    cameraMovements: ['dolly-in', 'push-in', 'crane-up', 'orbit', 'tracking', 'static'],
    transitions: ['dip-to-black', 'crossfade', 'cut', 'fade'],
    moods: ['brooding', 'anticipation', 'awe', 'triumphant', 'intimate'],
    beats: ['hook', 'tension', 'reveal', 'desire', 'payoff'],
    chapterThemes: ['The Spark', 'The Rise', 'The Reveal'],
    defaultCallToAction: 'Discover more',
    threeEnvironment: 'night',
    threeLighting: 'dramatic',
    captionPreset: 'minimal',
    wordsPerSecond: 2.2,
    guidance: 'Few words, big images. Every scene should feel like a frame from a film trailer; end on the brand.',
  },
  promo: {
    genre: 'promo',
    label: 'Promo',
    pacing: 'Upbeat and punchy (~3.5 s per scene): hook, benefits, proof, offer.',
    tone: ['energetic', 'confident', 'friendly', 'upbeat'],
    audience: 'Prospective customers comparing options',
    objective: 'Drive interest in {title} and convert viewers with a clear offer.',
    visualDescription: 'Bright, clean, product-forward layouts with bold color blocks, crisp feature cards and big numbers.',
    typography: 'Geometric sans-serif headlines with medium-weight body copy',
    motionLanguage: 'Snappy slides, pops and wipes synced to an upbeat track',
    palette: ['#2563EB', '#F97316', '#0F172A', '#F8FAFC', '#22C55E'],
    bodyTemplates: ['split-feature', 'stat-counter', 'kinetic-text', 'bullet-list', 'quote'],
    openingTemplate: 'title-card',
    closingTemplate: 'cta-end-card',
    fallbackTemplate: 'split-feature',
    shotTypes: ['medium', 'close-up', 'insert', 'wide', 'overhead'],
    cameraMovements: ['push-in', 'pan-right', 'truck-left', 'static', 'zoom-in'],
    transitions: ['slide', 'wipe', 'zoom', 'cut'],
    moods: ['excited', 'confident', 'playful', 'urgent'],
    beats: ['hook', 'problem', 'benefit', 'proof', 'offer'],
    chapterThemes: ['Meet the product', 'Why it matters', 'Proof', 'The offer'],
    defaultCallToAction: 'Get started today',
    threeEnvironment: 'studio',
    threeLighting: 'high-key',
    captionPreset: 'bold-center',
    wordsPerSecond: 2.6,
    guidance: 'Lead with the strongest benefit, back it with proof (numbers, testimonials) and close with one clear offer.',
  },
  'sop-training': {
    genre: 'sop-training',
    label: 'SOP / procedure training',
    pacing: 'Deliberate (~9 s per step); exactly one action per scene; repeat critical cautions.',
    tone: ['clear', 'precise', 'instructional', 'calm'],
    audience: 'Operators and new staff who must perform the procedure correctly',
    objective: 'Teach the {title} procedure step by step so it is performed safely and consistently.',
    visualDescription:
      'Clean, high-legibility instructional frames with large step numbers, simple icons and amber caution banners on neutral backgrounds.',
    typography: 'Highly legible sans-serif, large step numbers, short imperative sentences',
    motionLanguage: 'Calm fades and slides; nothing distracting from the instruction',
    palette: ['#0F766E', '#F59E0B', '#0F172A', '#F1F5F9', '#DC2626'],
    bodyTemplates: ['step-instruction', 'bullet-list', 'lower-third'],
    openingTemplate: 'title-card',
    closingTemplate: 'bullet-list',
    fallbackTemplate: 'step-instruction',
    shotTypes: ['medium', 'close-up', 'insert', 'overhead', 'pov'],
    cameraMovements: ['static', 'push-in', 'tilt-down', 'static'],
    transitions: ['fade', 'cut', 'slide'],
    moods: ['focused', 'methodical', 'reassuring', 'attentive'],
    beats: ['step', 'step', 'step', 'check'],
    chapterThemes: ['Preparation & safety', 'Procedure', 'Verification & wrap-up'],
    defaultCallToAction: null,
    threeEnvironment: 'warehouse',
    threeLighting: 'soft',
    captionPreset: 'lower',
    wordsPerSecond: 2.2,
    guidance:
      'Use imperative instructions ("Turn the valve clockwise"). Number the steps, call out safety cautions explicitly and finish with a recap/checklist.',
  },
  'corporate-training': {
    genre: 'corporate-training',
    label: 'Corporate training',
    pacing: 'Measured (~10 s per scene) with a recap moment every few scenes.',
    tone: ['professional', 'supportive', 'clear', 'engaging'],
    audience: 'Employees completing workplace training',
    objective: 'Help employees understand and apply {title} in their daily work.',
    visualDescription: 'Polished corporate look: brand colors, generous whitespace, iconography and presenter-style lower thirds.',
    typography: 'Neutral humanist sans-serif with clear hierarchy',
    motionLanguage: 'Gentle slides, builds and crossfades',
    palette: ['#1D4ED8', '#0EA5E9', '#0F172A', '#F8FAFC', '#F59E0B'],
    bodyTemplates: ['bullet-list', 'quote', 'stat-counter', 'split-feature', 'step-instruction', 'lower-third'],
    openingTemplate: 'title-card',
    closingTemplate: 'bullet-list',
    fallbackTemplate: 'bullet-list',
    shotTypes: ['medium', 'wide', 'close-up', 'two-shot', 'over-the-shoulder'],
    cameraMovements: ['static', 'push-in', 'pan-right', 'truck-right'],
    transitions: ['fade', 'slide', 'crossfade'],
    moods: ['encouraging', 'focused', 'reflective', 'positive'],
    beats: ['why it matters', 'concept', 'example', 'practice', 'recap'],
    chapterThemes: ['Why this matters', 'Core concepts', 'In practice', 'Recap & next steps'],
    defaultCallToAction: null,
    threeEnvironment: 'city',
    threeLighting: 'soft',
    captionPreset: 'lower',
    wordsPerSecond: 2.4,
    guidance: 'Explain why it matters, teach the concept, show a realistic workplace example, then recap the key takeaways.',
  },
  comedy: {
    genre: 'comedy',
    label: 'Comedy',
    pacing: 'Snappy comedic timing (~4 s per scene): setup, escalation, punchline; leave a beat after each joke.',
    tone: ['funny', 'absurd', 'playful', 'witty'],
    audience: 'Viewers looking for a laugh',
    objective: 'Make viewers laugh with an escalating comedic take on {title}.',
    visualDescription:
      'Bright, exaggerated cartoon staging with expressive characters, bold outlines, speech bubbles and comic timing.',
    typography: 'Chunky rounded display type in speech bubbles',
    motionLanguage: 'Squash-and-stretch, bounces, shakes, spins and smash cuts',
    palette: ['#FDE047', '#F43F5E', '#1E1B4B', '#FFFFFF', '#38BDF8'],
    bodyTemplates: ['cartoon-scene', 'cartoon-scene', 'kinetic-text', 'cartoon-scene'],
    openingTemplate: 'cartoon-scene',
    closingTemplate: 'cartoon-scene',
    fallbackTemplate: 'cartoon-scene',
    shotTypes: ['wide', 'medium', 'close-up', 'two-shot', 'extreme-close-up'],
    cameraMovements: ['static', 'handheld', 'zoom-in', 'pan-left', 'push-in'],
    transitions: ['cut', 'zoom', 'wipe', 'cut'],
    moods: ['silly', 'awkward', 'chaotic', 'gleeful', 'deadpan'],
    beats: ['setup', 'setup', 'escalation', 'escalation', 'punchline'],
    chapterThemes: ['The setup', 'Things escalate', 'The punchline'],
    defaultCallToAction: null,
    threeEnvironment: 'studio',
    threeLighting: 'high-key',
    captionPreset: 'karaoke',
    wordsPerSecond: 2.8,
    guidance: 'Rule of three: set up an expectation, escalate it absurdly, then subvert it. Keep dialogue short and quotable.',
  },
  cartoon: {
    genre: 'cartoon',
    label: 'Cartoon',
    pacing: 'Lively (~4 s per scene) with clear story beats and visual gags.',
    tone: ['whimsical', 'playful', 'warm', 'silly'],
    audience: 'Families and fans of animated stories',
    objective: 'Tell a delightful animated story about {title}.',
    visualDescription: 'Flat vector cartoon world with rounded shapes, saturated colors and bouncy, expressive characters.',
    typography: 'Rounded, friendly display type',
    motionLanguage: 'Bouncy squash-and-stretch with springy easing and playful wipes',
    palette: ['#22D3EE', '#FB7185', '#312E81', '#FEF3C7', '#A3E635'],
    bodyTemplates: ['cartoon-scene'],
    openingTemplate: 'cartoon-scene',
    closingTemplate: 'cartoon-scene',
    fallbackTemplate: 'cartoon-scene',
    shotTypes: ['wide', 'medium', 'close-up', 'establishing', 'two-shot'],
    cameraMovements: ['pan-right', 'static', 'zoom-in', 'tracking', 'crane-up'],
    transitions: ['wipe', 'cut', 'zoom', 'fade'],
    moods: ['cheerful', 'curious', 'mischievous', 'surprised', 'joyful'],
    beats: ['introduction', 'discovery', 'mishap', 'chase', 'gag', 'resolution'],
    chapterThemes: ['Once upon a time', 'Uh-oh!', 'The big chase', 'Happily ever after'],
    defaultCallToAction: null,
    threeEnvironment: 'forest',
    threeLighting: 'soft',
    captionPreset: 'karaoke',
    wordsPerSecond: 2.5,
    guidance: 'A lovable character wants something, things go comically wrong, and it ends warmly. Every scene needs a visual gag.',
  },
  'motion-graphics': {
    genre: 'motion-graphics',
    label: 'Motion graphics',
    pacing: 'Rhythmic (~4 s per scene), cut to the music; alternate type-driven and abstract moments.',
    tone: ['modern', 'dynamic', 'sleek', 'bold'],
    audience: 'Digital-savvy viewers',
    objective: 'Communicate {title} through striking typography and abstract motion.',
    visualDescription: 'Abstract geometric shapes, gradients and kinetic type in a tight color system.',
    typography: 'Bold grotesk headlines with tight leading',
    motionLanguage: 'Kinetic typography, shape morphs, zoom transitions and match cuts',
    palette: ['#7C3AED', '#06B6D4', '#0B1020', '#F8FAFC', '#F472B6'],
    bodyTemplates: ['kinetic-text', 'floating-shapes', 'stat-counter', 'kinetic-text', 'bullet-list'],
    openingTemplate: 'title-card',
    closingTemplate: 'kinetic-text',
    fallbackTemplate: 'kinetic-text',
    shotTypes: ['wide', 'close-up', 'macro', 'insert'],
    cameraMovements: ['push-in', 'orbit', 'zoom-in', 'pan-left', 'dolly-out'],
    transitions: ['zoom', 'wipe', 'slide', 'blur'],
    moods: ['electric', 'sleek', 'hypnotic', 'confident'],
    beats: ['hook', 'statement', 'data', 'idea', 'payoff'],
    chapterThemes: ['Hook', 'Ideas in motion', 'The takeaway'],
    defaultCallToAction: null,
    threeEnvironment: 'city',
    threeLighting: 'dramatic',
    captionPreset: 'bold-center',
    wordsPerSecond: 2.5,
    guidance: 'Let typography carry the message; use abstract 3D shapes for rhythm between statements.',
  },
  'product-3d': {
    genre: 'product-3d',
    label: '3D product showcase',
    pacing: 'Smooth and premium (~5 s per scene): reveal, details, benefits, hero shot.',
    tone: ['premium', 'precise', 'innovative', 'confident'],
    audience: 'Shoppers evaluating the product',
    objective: 'Showcase {title} in 3D so viewers understand its design and benefits.',
    visualDescription:
      'Studio-lit 3D product hero shots on seamless backdrops with soft reflections and floating feature callouts.',
    typography: 'Clean, technical sans-serif with thin weights',
    motionLanguage: 'Slow orbits, turntable spins, dolly moves and crossfades',
    palette: ['#111827', '#E5E7EB', '#3B82F6', '#F8FAFC', '#F59E0B'],
    bodyTemplates: ['product-turntable', 'split-feature', 'product-turntable', 'stat-counter', 'floating-shapes'],
    openingTemplate: 'logo-reveal-3d',
    closingTemplate: 'product-turntable',
    fallbackTemplate: 'split-feature',
    shotTypes: ['macro', 'close-up', 'extreme-close-up', 'wide', 'insert'],
    cameraMovements: ['orbit', 'dolly-in', 'crane-up', 'push-in', 'static'],
    transitions: ['crossfade', 'blur', 'fade', 'dip-to-black'],
    moods: ['sleek', 'precise', 'premium', 'bold'],
    beats: ['reveal', 'design detail', 'feature', 'benefit', 'hero'],
    chapterThemes: ['Unveiling', 'Design & features', 'Why you will love it'],
    defaultCallToAction: 'Order yours today',
    threeEnvironment: 'studio',
    threeLighting: 'soft',
    captionPreset: 'minimal',
    wordsPerSecond: 2.3,
    guidance: 'Treat the product as the hero: alternate 3D turntable shots with feature callouts; finish on a hero shot and the offer.',
  },
  'real-estate': {
    genre: 'real-estate',
    label: 'Real estate',
    pacing: 'Elegant and unhurried (~5 s per scene): arrival, interiors, highlights, neighborhood, viewing.',
    tone: ['inviting', 'elegant', 'warm', 'aspirational'],
    audience: 'Home buyers and renters',
    objective: 'Present {title} so buyers want to book a viewing.',
    visualDescription:
      'Bright, airy interiors and golden-hour exteriors with elegant listing cards, location pins and feature chips.',
    typography: 'Elegant serif headlines with clean sans-serif details',
    motionLanguage: 'Smooth gimbal glides, slow pans and gentle crossfades',
    palette: ['#1F2937', '#B08D57', '#F9FAFB', '#0F172A', '#10B981'],
    bodyTemplates: ['property-showcase', 'split-feature', 'lower-third', 'property-showcase', 'stat-counter'],
    openingTemplate: 'title-card',
    closingTemplate: 'property-showcase',
    fallbackTemplate: 'property-showcase',
    shotTypes: ['establishing', 'wide', 'medium', 'overhead', 'insert'],
    cameraMovements: ['dolly-in', 'pan-right', 'crane-up', 'truck-left', 'tracking'],
    transitions: ['crossfade', 'fade', 'slide', 'dip-to-white'],
    moods: ['welcoming', 'serene', 'luxurious', 'bright'],
    beats: ['arrival', 'living spaces', 'kitchen', 'bedrooms', 'amenities', 'neighborhood'],
    chapterThemes: ['Arrival', 'Inside the home', 'Lifestyle & location'],
    defaultCallToAction: 'Book a private viewing',
    threeEnvironment: 'sunset',
    threeLighting: 'soft',
    captionPreset: 'lower',
    wordsPerSecond: 2.3,
    guidance: 'Sell the lifestyle, not just the square meters: lead with the hero exterior, walk room by room, then location and price.',
  },
  explainer: {
    genre: 'explainer',
    label: 'Explainer',
    pacing: 'Clear and steady (~7 s per scene): question, how it works, example, benefit.',
    tone: ['clear', 'friendly', 'curious', 'helpful'],
    audience: 'Curious viewers new to the topic',
    objective: 'Explain {title} simply so viewers understand how it works and why it matters.',
    visualDescription: 'Friendly flat illustrations, simple diagrams and icon-driven layouts with a clear visual hierarchy.',
    typography: 'Friendly rounded sans-serif',
    motionLanguage: 'Builds, reveals and simple diagram animations',
    palette: ['#4F46E5', '#F59E0B', '#111827', '#F9FAFB', '#10B981'],
    bodyTemplates: ['split-feature', 'bullet-list', 'stat-counter', 'kinetic-text', 'cartoon-scene'],
    openingTemplate: 'title-card',
    closingTemplate: 'bullet-list',
    fallbackTemplate: 'split-feature',
    shotTypes: ['medium', 'close-up', 'wide', 'overhead', 'insert'],
    cameraMovements: ['push-in', 'static', 'pan-right', 'zoom-in'],
    transitions: ['slide', 'fade', 'wipe', 'cut'],
    moods: ['curious', 'enlightening', 'optimistic', 'clear'],
    beats: ['question', 'problem', 'how it works', 'example', 'benefit'],
    chapterThemes: ['The question', 'How it works', 'Why it matters'],
    defaultCallToAction: 'Learn more',
    threeEnvironment: 'studio',
    threeLighting: 'high-key',
    captionPreset: 'bold-center',
    wordsPerSecond: 2.5,
    guidance: 'One idea per scene. Use analogies and concrete examples; avoid jargon or define it immediately.',
  },
  presentation: {
    genre: 'presentation',
    label: 'Presentation',
    pacing: 'Structured (~10 s per scene), like a well-paced slide deck.',
    tone: ['informative', 'structured', 'confident', 'professional'],
    audience: 'Stakeholders and meeting attendees',
    objective: 'Present {title} as a clear, structured narrative with key data points.',
    visualDescription: 'Slide-like layouts on a strong grid with data callouts and minimal decoration.',
    typography: 'Clean sans-serif with strong hierarchy',
    motionLanguage: 'Subtle builds and slide transitions',
    palette: ['#0F172A', '#38BDF8', '#F8FAFC', '#1E293B', '#FACC15'],
    bodyTemplates: ['bullet-list', 'stat-counter', 'quote', 'split-feature', 'title-card'],
    openingTemplate: 'title-card',
    closingTemplate: 'bullet-list',
    fallbackTemplate: 'bullet-list',
    shotTypes: ['medium', 'wide', 'insert', 'close-up'],
    cameraMovements: ['static', 'push-in', 'pan-right'],
    transitions: ['fade', 'slide', 'cut'],
    moods: ['focused', 'assured', 'analytical', 'inspiring'],
    beats: ['agenda', 'context', 'insight', 'data', 'recommendation'],
    chapterThemes: ['Agenda & context', 'Key insights', 'Recommendations'],
    defaultCallToAction: null,
    threeEnvironment: 'city',
    threeLighting: 'soft',
    captionPreset: 'minimal',
    wordsPerSecond: 2.3,
    guidance: 'Agenda first, then insights backed by data, then concrete recommendations and next steps.',
  },
  'social-short': {
    genre: 'social-short',
    label: 'Social short',
    pacing: 'Very fast (~2.5 s per scene); hook in the first second, payoff before viewers swipe.',
    tone: ['punchy', 'trendy', 'energetic', 'playful'],
    audience: 'Scrollers on TikTok, Reels and Shorts',
    objective: 'Stop the scroll and deliver {title} in seconds.',
    visualDescription: 'Vertical-first, high-contrast frames with oversized captions, bold type and quick cuts.',
    typography: 'Heavy display type with outlines',
    motionLanguage: 'Jump cuts, zoom punches and kinetic captions',
    palette: ['#FF0050', '#00F2EA', '#0A0A0A', '#FFFFFF', '#FACC15'],
    bodyTemplates: ['kinetic-text', 'stat-counter', 'kinetic-text', 'floating-shapes', 'cartoon-scene'],
    openingTemplate: 'kinetic-text',
    closingTemplate: 'kinetic-text',
    fallbackTemplate: 'kinetic-text',
    shotTypes: ['close-up', 'pov', 'medium', 'extreme-close-up'],
    cameraMovements: ['zoom-in', 'handheld', 'push-in', 'pan-left'],
    transitions: ['zoom', 'cut', 'slide', 'wipe'],
    moods: ['hype', 'surprising', 'fun', 'urgent'],
    beats: ['hook', 'twist', 'value', 'payoff'],
    chapterThemes: ['Hook', 'Payoff'],
    defaultCallToAction: 'Follow for more',
    threeEnvironment: 'night',
    threeLighting: 'dramatic',
    captionPreset: 'bold-center',
    wordsPerSecond: 2.9,
    guidance: 'Hook in the first line, one idea per beat, end with a loopable payoff or a quick call to action.',
  },
  'long-form': {
    genre: 'long-form',
    label: 'Long-form',
    pacing: 'Unhurried (~12 s per scene) with chapter cards and recurring structure.',
    tone: ['thoughtful', 'informative', 'engaging', 'narrative'],
    audience: 'Viewers ready for an in-depth story',
    objective: 'Take viewers on an in-depth, well-structured journey through {title}.',
    visualDescription: 'Documentary-style sequences mixing chapter cards, quotes, data and illustrative frames.',
    typography: 'Editorial serif headlines with sans-serif captions',
    motionLanguage: 'Unhurried pans, slow zooms, crossfades and chapter cards',
    palette: ['#1E293B', '#E2B714', '#F8FAFC', '#0F172A', '#64748B'],
    bodyTemplates: ['split-feature', 'bullet-list', 'quote', 'kinetic-text', 'stat-counter', 'lower-third'],
    openingTemplate: 'title-card',
    closingTemplate: 'quote',
    fallbackTemplate: 'bullet-list',
    shotTypes: ['establishing', 'wide', 'medium', 'close-up', 'insert', 'over-the-shoulder'],
    cameraMovements: ['pan-right', 'push-in', 'static', 'dolly-in', 'tilt-up', 'pull-out'],
    transitions: ['crossfade', 'fade', 'dip-to-black', 'cut'],
    moods: ['reflective', 'curious', 'dramatic', 'hopeful', 'contemplative'],
    beats: ['context', 'story', 'evidence', 'perspective', 'reflection'],
    chapterThemes: ['Origins', 'The turning point', 'Inside the story', 'Lessons learned', 'What comes next'],
    defaultCallToAction: null,
    threeEnvironment: 'forest',
    threeLighting: 'soft',
    captionPreset: 'lower',
    wordsPerSecond: 2.3,
    guidance: 'Give every chapter its own arc (context, story, evidence, reflection) and open each chapter with a title card.',
  },
  'reference-based': {
    genre: 'reference-based',
    label: 'Reference-based',
    pacing: "Match the reference's pacing (average shot length and cut rhythm).",
    tone: ['faithful', 'stylish', 'consistent', 'polished'],
    audience: 'The same audience as the reference material',
    objective: 'Recreate the look, pacing and feel of the reference for {title}.',
    visualDescription: "Matches the reference's palette, framing, typography and pacing while telling the new story.",
    typography: "Matched to the reference's typography",
    motionLanguage: "Mirrors the reference's camera language and cut rhythm",
    palette: ['#111827', '#F3F4F6', '#EF4444', '#0F172A', '#3B82F6'],
    bodyTemplates: ['kinetic-text', 'split-feature', 'quote', 'stat-counter', 'floating-shapes'],
    openingTemplate: 'title-card',
    closingTemplate: 'kinetic-text',
    fallbackTemplate: 'kinetic-text',
    shotTypes: ['wide', 'medium', 'close-up', 'insert'],
    cameraMovements: ['push-in', 'static', 'pan-right', 'dolly-in'],
    transitions: ['cut', 'crossfade', 'fade'],
    moods: ['polished', 'confident', 'focused', 'stylish'],
    beats: ['hook', 'story', 'detail', 'payoff'],
    chapterThemes: ['Opening', 'Development', 'Finale'],
    defaultCallToAction: 'Learn more',
    threeEnvironment: 'studio',
    threeLighting: 'dramatic',
    captionPreset: 'minimal',
    wordsPerSecond: 2.5,
    guidance:
      'Borrow structure and style (palette, shot types, transitions, pacing) from the reference profile, never its specific content or brand.',
  },
};

export function genreProfile(genre: VideoGenre): GenreProfile {
  return GENRE_PROFILES[genre];
}

/** Deterministically cycles through a non-empty list. */
export function cycle<T>(items: NonEmpty<T>, index: number): T {
  return items[((index % items.length) + items.length) % items.length] ?? items[0];
}

/**
 * Genre-appropriate motion2d template used when the chosen engine is unavailable:
 * `title-card` for the first scene, `cta-end-card` for the last when a CTA exists, else the genre default.
 */
export function coercionTemplateFor(
  genre: VideoGenre,
  position: { isFirst: boolean; isLast: boolean; hasCallToAction: boolean },
): Motion2DTemplateId {
  if (position.isFirst) return 'title-card';
  if (position.isLast && position.hasCallToAction) return 'cta-end-card';
  return GENRE_PROFILES[genre].fallbackTemplate;
}
